version: '3'

services:
  mariadb:
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    restart: always
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    networks:
      - inception
    depends_on:
      - wordpress

  redis:
    build:
      context: requirements/bonus/redis/
      dockerfile: Dockerfile
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inception

  vsftpd:
    build:
      context: requirements/bonus/vsftpad/
      dockerfile: Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    container_name: vsftpd
    restart: always
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
     - inception

  adminer:
    build:
      context: requirements/bonus/adminer/
      dockerfile: Dockerfile
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
     - inception
    depends_on:
      - mariadb

  website:
    build:
      context: requirements/bonus/website/
      dockerfile: Dockerfile
    container_name: website
    restart: always
    ports:
      - "80:80"

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
